[package]
name = "s0ra-os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.22"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.4"
volatile = "0.2.6"

[features]
